services:
  # Backend API
  - type: web
    name: ordenaya-api
    runtime: node
    rootDir: server
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres.vxjzrybssqhjifzaprpl:OwGXZlidILHXE4bi@aws-1-us-east-1.pooler.supabase.com:5432/postgres
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://ordenaya-web.onrender.com
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  # Frontend Estático (Static Site)
  - type: static
    name: ordenaya-web
    rootDir: client
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://ordenaya-api.onrender.com/api
      - key: VITE_SOCKET_URL
        value: https://ordenaya-api.onrender.com