# Exported from Render on 2026-04-07T19:26:51Z
version: "1"
services:
- type: web
  name: ordenaya-api
  runtime: node
  repo: https://github.com/wilmo9808/restaurant-app
  plan: starter
  envVars:
  - key: CLOUDINARY_API_SECRET
    sync: false
  - key: CLOUDINARY_API_KEY
    sync: false
  - key: CLOUDINARY_CLOUD_NAME
    sync: false
  - key: CLIENT_URL
    sync: false
  - key: JWT_SECRET
    sync: false
  - key: DATABASE_URL
    sync: false
  - key: NODE_ENV
    sync: false
  region: oregon
  buildCommand: npm install --omit=dev
  startCommand: npm start
  autoDeployTrigger: commit
  rootDir: server