services:
  - type: web
    name: ordenaya-api
    runtime: node
    rootDir: server
    buildCommand: npm install && npm install --save-dev @types/express @types/node @types/bcryptjs @types/jsonwebtoken @types/cors @types/multer @types/xlsx && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres.vxjzrybssqhjifzaprpl:OwGXZlidILHXE4bi@aws-1-us-east-1.pooler.supabase.com:5432/postgres
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://ordenaya-web.onrender.com
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false